spring: 
  profiles: 
    acrive: 
    - dev 
  
---
spring: 
  profiles: dev     #开发环境
  application: 
    name: microservicecloud-config-eureka-service-dev
    
server: 
  port: 7001
 
eureka: 
  instance:
    #单机版
    #hostname: localhost #eureka服务端的实例名称
    
    #ureka集群
    hostname: eureka7001.com #eureka服务端的实例名称
  client: 
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url: 
       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
       #即Eureka客户端需连接通过此地址连接Eureka Server
       #单机版
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
       #集群版
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
    
    
---
spring: 
  profiles: test     #测试环境
  application: 
    name: microservicecloud-config-eureka-service-test
    
server: 
  port: 7001
 
eureka: 
  instance:
    #单机版
    #hostname: localhost #eureka服务端的实例名称
    
    #ureka集群
    hostname: eureka7001.com #eureka服务端的实例名称
  client: 
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url: 
       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
       #即Eureka客户端需连接通过此地址连接Eureka Server
       #单机版
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
       #集群版
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
    
#请保存为UTF-8格式

 

